### ISSUE TITLE
Failed to create NDA token

### ISSUE THREAD

**Issue by aporter1350** [DCAN-Labs/nda-abcd-s3-downloader#35] opened 2022-09-26 15:56 UTC
After eRA commons updated their login to require dual authentication with Login.gov on September 23, 2022 I am no longer able to sign in to NIMH Data Archives using my config.ini  file from the download.py script. I have not changed anything with my config file and was able to download data fine before the eRA commons update. I am able to successfully login to the nda.nih website, NDA Downloader and eRA commons. I tried resetting my password with eRA commons then create a new config.ini file but I still am unable to create an NDA token. Does someone know why this might be occurring or how to resolve this issue?

![Screen Shot 2022-09-26 at 10 55 22 AM](https://user-images.githubusercontent.com/25799498/192323825-980b41ad-1a81-4732-9652-1761b0b8a56e.png)

**Comment by perronea** [comment] 2022-09-26 16:44
@aporter1350 The only way to download data from the NDA now is by creating a data package through the NDA's website and then downloading data from that package using `downloadcmd` from the [nda-tools](https://github.com/NDAR/nda-tools).

I'm currently working on updating the documentation and code base to reflect this. I'll close this issue when I've pushed my changes.

The NDA is also working on an API to create these data packages pragmatically from the command line, although there is no timeline yet for this deliverable.

**Comment by aporter1350** [comment] 2022-09-26 18:02
Thanks for the update!

**Comment by aporter1350** [comment] 2022-10-05 15:22
Hi @perronea do you know what the package name is for the abcc dataset? The downloadcmd tool requires the packageID. I created a mINDAR using this package (https://nda.nih.gov/edit_collection.html?id=3165) but the data associated with the s3 links from the manifest.txt file is not located with this package.

**Comment by iamdamion** [comment] 2022-10-17 02:33
@perronea I've been trying to work on a workaround for this and wonder if you have any insight. I thought maybe using the downloadcmd function from the nda-tools set would work with a txt file with the s3 paths. However, it's telling me the paths aren't valid. Have you found anything while working on this?

**Comment by cassandrajustinelowe** [comment] 2022-10-20 15:07
Also need to sort out a workaround. I have tried using NDA tools but the s3 links don’t work. I have nothing else to add, but want to comment to get the updates.

**Comment by vgonzenbach** [comment] 2022-10-25 14:12
I'm also having issues with this.

**Comment by ebridge2** [comment] 2022-11-02 07:41
Fourthing needing updates here!

**Comment by ebridge2** [comment] 2022-11-02 07:42
Fourthing subscribing for updates here :)

**Comment by QianLi9423** [comment] 2022-12-02 14:13
> t

Hello, I'm also having issues with this.. Have you resolved it? Could you share me your method?

**Comment by dyhan316** [comment] 2022-12-04 13:49
@perronea  Is it possible to download by setting the below thing to True, so that the images themselves are inside the data package, later to be downloaded by `downloadcmd` ? 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/34816251/205494264-217a3178-2531-4158-8807-b082e4b3274a.png">

**Comment by perronea** [comment] 2022-12-19 15:39
@yoyo9423 Unfortunately not. While selecting "Include associated data files" will be necessary the current implementation does not work. The problem is that the data package is simply too large with all of the data included. The entire ABCC dataset is currently about 180TB and the API within downloadcmd will timeout if you try to request anything from it. However, we found a workaround that looks promising. Instead of downloading everything we can incrementally query the files that are associated with a data package and compile a database of tokens and associated data files on the user side that we can then query in order to selectively download files from the data package. I'm almost finished with the development and I should be releasing a new version of the downloader in the next couple days. Thank you for your patience.

**Comment by yoyo9423** [comment] 2023-02-01 09:41
> @yoyo9423 Unfortunately not. While selecting "Include associated data files" will be necessary the current implementation does not work. The problem is that the data package is simply too large with all of the data included. The entire ABCC dataset is currently about 180TB and the API within downloadcmd will timeout if you try to request anything from it. However, we found a workaround that looks promising. Instead of downloading everything we can incrementally query the files that are associated with a data package and compile a database of tokens and associated data files on the user side that we can then query in order to selectively download files from the data package. I'm almost finished with the development and I should be releasing a new version of the downloader in the next couple days. Thank you for your patience.

**Comment by yoyo9423** [comment] 2023-02-01 09:55
@perronea Dear contributors, have you solved the issue and when will the newest version be released? Looking forward to the great downloader!

**Comment by adpines** [comment] 2023-02-07 00:18
Hey @perronea and/or @ericearl, thanks for all your work on this: have leveraged 3165 heavily previously. Just confirming that this NDA password issue is unresolved, and that there is no other way to access the dataset given nda-tools issues? I can corroborate prior posts about user/passwords that work for DEAP failing to create an NDA token for this tool (and can also confirm that it worked perfectly prior to the NDA password "updates")

**Comment by ericearl** [comment] 2023-02-11 15:23
@adpines I'm no longer with DCAN-Labs, but last I heard I think they are still working on a fix or have some workaround due to the NDA limitations on big data like this. But yeah, @perronea or @ericfeczko can say for sure so I defer to the DCAN-Labs team.

**Comment by adpines** [comment] 2023-02-11 17:05
> @adpines I'm no longer with DCAN-Labs, but last I heard I think they are still working on a fix or have some workaround due to the NDA limitations on big data like this. But yeah, @perronea or @ericfeczko can say for sure so I defer to the DCAN-Labs team.

gotchya, sorry to tag you then. Thanks for weighing in and hope you are well!

**Comment by perronea** [comment] 2023-03-13 20:11
I've replaced the token generator and refactored the download method to leverage the NDA package API in a way that avoids the Timeout errors that users were reporting with downloadcmd. Please follow the new documentation on the v1.0.0 pre-release of this repository to access Collection 3165 and please open a new issue if you encounter any further problems with this utility.

**Closed by perronea** 2023-03-13 20:11 UTC
