### ISSUE TITLE
Failed to create NDA token error

### ISSUE THREAD

**Issue by iamdamion** [DCAN-Labs/nda-abcd-s3-downloader#14] opened 2020-12-14 19:15 UTC
I am getting the following error trying to use the downloader:

Derivatives downloader called at 2020:12:14 13:11 with:
Failed to create NDA token.
Failed to create NDA token using the username and decrypted password from /Users/d/.abcd2bids/config.ini.

I verified my login info on the NDA site.

**Comment by perronea** [comment] 2020-12-14 21:55
It looks like it's trying to read your encrypted username/pw from the config.ini file. Is it possible that the password there is outdated or incorrect? I would recommend removing that file and then re-running the download script which will then prompt you for your credentials.

**Comment by iamdamion** [comment] 2020-12-14 22:12
Sorry, should have mentioned I had already tried that before creating this issue. Are any of you able to get it to work? It was working for me last week, but was giving mean error that the manifest file had an error on some line. So I re-downloaded that file from NDA (thinking maybe that file was incomplete) and now today I'm getting this error. I'm now wondering if maybe it's an AWS issue since this step worked for me last week. (There are some reports that it is down in some areas)

**Comment by iamdamion** [comment] 2020-12-14 22:26
After digging into the script a little, I see that it's supposed to be adding an entry to .aws/credentials with my access key, etc. I backed up that file and deleted that entry and re-ran and it's not recreating that entry. It looks like for whatever reason, it's not updating that info. 

I also tried updating that info directly from my NDA download manager tool (fresh info) and re-running, but it's still giving me that error. So I'm thinking it's not re-writing that file because something is stopping the NDA login, and it also won't get past that login step even with manually entered info. Without knowing if it's just me, I can't tell if it's a general issue with logging in right now or if I perhaps need to try to delete all the hidden files it previously created and try again...

**Comment by iamdamion** [comment] 2020-12-15 19:40
Still not having any luck. If you could at least verify that it is working for people on your side, it would help me start to narrow down why this is happening now, but didn't last week. Thanks.

**Comment by mharms** [comment] 2020-12-15 23:39
The ABCD-STUDY fork (https://github.com/ABCD-STUDY/nda-abcd-s3-downloader) worked for me fine on Friday.  I just  deleted my config.ini, and confirmed that it is still working for me now as well.

**Comment by iamdamion** [comment] 2020-12-16 01:05
> The ABCD-STUDY fork (https://github.com/ABCD-STUDY/nda-abcd-s3-downloader) worked for me fine on Friday. I just deleted my config.ini, and confirmed that it is still working for me now as well.

Thanks. This at least narrows it down, although I don't know why my login works on the site, etc, but not with this. And it was also working last week with this script. I guess I'll try to figure this out elsewhere. Thanks.

**Comment by iamdamion** [comment] 2020-12-18 23:24
Reopening this because @ericearl helped me figure it out on a support call. We found that there is something wacky happening with the ssl certificate. (Quick brainstorming our thoughts are maybe it expired between my uses of the downloader script and that's why this happened for me. Anyway, we used this workaround that perhaps could be used for a check in future versions of the script. Also of note, I am running this on a mac, so something about how Mojave (10.14.5) handles certs might be at play also?

The import ssl and line below are what we added. 

`

    def __make_request(self, request_message):
        logging.debug('making post request to %s' % self.url)

        headers = {
            'SOAPAction': '"generateToken"',
            'Content-Type': 'text/xml; charset=utf-8'
        }
        request = urllib_request.Request(self.url, data=request_message, headers=headers)
        logging.debug(request)
        # print('test print:')
        import ssl
        ssl._create_default_https_context = ssl._create_unverified_context
        # print(request_message)
        # print('url message')
        # print(self.url)

        response = urllib_request.urlopen(request)
        # print('return')
        return self.__parse_response(response.read())
`

**Comment by ericearl** [comment] 2020-12-22 21:50
@perronea This seems to effect Mac users and not others.

**Comment by kimberlylray** [comment] 2021-04-06 19:44
Hey @iamdamion I think I am running into the same issue on my mac.  Ive also deleted my config.ini file and confirmed my password. Could you elaborate on how you imported you ssl and created the default line you shared? Thanks!

**Comment by iamdamion** [comment] 2021-04-06 20:00
> Hey @iamdamion I think I am running into the same issue on my mac. Ive also deleted my config.ini file and confirmed my password. Could you elaborate on how you imported you ssl and created the default line you shared? Thanks!

The above is what we changed in the nda_aws_token_generator.py script that is in the /src/ folder in the nda-abcd-s3-downloader-master folder. All you have to do is edit your code to be the same as that (the import and create default https lines are the only we added...it's been a while so I'm not 100% sure) and it should work. (The import ssl line is just importing a python library to handle ssl, which I believe is what you were asking? Unless I'm not understanding what you mean?) 

There is also a hidden folder in your user folder (show hidden in finder with "cmd + shift + .") called /.aws/ that I had to delete first if I remember correctly. Or it might get overwritten once the above fix is implemented. I don't think it should matter but if you run into issues try deleting that first.

**Comment by kimberlylray** [comment] 2021-04-06 20:45
@iamdamion  yep - thats what I was asking!  
I missed that you made change to that specific file. I added those two lines, removed the config file, also deleted the /.aws/ directory.  Unfortunately I get the same error: 

ERROR:root:response had error message: Invalid username and/or password
Failed to create NDA token.
Failed to create NDA token using the username and decrypted password from /Users/PSYC/.abcd2bids/config.ini.

I noticed that I didnt have the .aws/credentials file, my .aws/ directory was empty.

**Comment by iamdamion** [comment] 2021-04-06 20:56
@kimberlylray  Yeah, that was the same thing happening to me (the empty folder) when I was getting the error. But that (above) was the only code change we made and that got it working. This was working for me until I was done downloading about 2 months ago (I'd doubt ABCD or AWS made another change).  

If you've done the following:
1. delete .abcd2bids hidden folder
2. delete .aws hidden folder
3. make the above script edit
...and it still doesn't work, my only other thought is maybe your OSX version? I know there was some wacky architecture update that broke freesurfer and stuff a while back, which is why I've stuck to Mojave 10.14.5 and won't update until I defend. This is a wild guess, but if you've updated maybe that is having some impact?

Maybe @ericearl can give some more advanced insight.

**Comment by kimberlylray** [comment] 2021-04-06 21:26
Thanks @iamdamion, Im still on High Sierra 10.13.6 because I thought UT had told us to hold off on updating. 
Any thoughts @ericearl on what else to try?

**Comment by ericearl** [comment] 2021-04-07 22:01
@iamdamion @kimberlylray I wonder if this has to do with the NDA's new release of the new download manager somehow?  @perronea Can you try our downloader out directly from your Mac with just a couple S3 links?

**Comment by obenshaindw** [comment] 2021-04-08 16:06
Hi all. NDA has updated password encryption to be more secure. If you have updated your password recently on the NDA application, or created an account recently the password encryption will be SHA256. We updated all of our client tools to be compatible with this change, but we did not update this python package.

I did want to point out this announcement that was sent out a couple of weeks ago: https://mailchi.mp/mail/new-nda-download-manager-tool-now-available?e=2f3deecfc4,  where we discuss general deprecation of the DataManager service and single-use FederationUser token. We are directing third party tools to have a look at the new package web service and developer documentation we have hosted on https://github.com/NDAR/nda-data-access-example-code with example code for how to use a list of S3 files with the package service to get tokens.  **The big difference here is that tokens must be requested for a specific file or files, from a specific user package, and the tokens can only be used to access those files**

I am working on a minor update to https://github.com/NDAR/nda_aws_token_generator that handles the possibility of a user's password being hashed with either SHA1 or SHA256.

**Comment by ericearl** [comment] 2021-04-13 20:19
@obenshaindw Thank you so much for your careful attention to our tool.  It is appreciated.  @perronea Can you review that pull request for inclusion into our codebase?  It might just fix @kimberlylray's problem.

**Comment by kimberlylray** [comment] 2021-04-13 20:56
@obenshaindw Thanks for those updates, It looks like my credentials are working now.  I ran download.py for a single subject, the output says ABCD-BIDS Downloader complete!  The output directory structure seems to have been created, however there aren't any files visible. 

@ericearl maybe this is where you are more familiar with the code?  

```
python3 download.py -i /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/Package_1187187/datastructure_manifest.txt -s subjects.txt -o /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject -d inputs.txt
Derivatives downloader called at 2021:04:13 15:37 with:
aws_access_key_id=removed
aws_secret_access_key=removed
security_token=removed

expiration=2021-04-14T08:37:55Z

	Log folder:	/Users/PSYC-klr3342
	S3 Spreadsheet:	/Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/Package_1187187/datastructure_manifest.txt
sys:1: DtypeWarning: Columns (0,1,2) have mixed types.Specify dtype option on import or set low_memory=False.
	Subjects:	subjects.txt
	Data Subsets:	inputs.txt

Reading in S3 links...
Creating unique download list...
Creating download commands...

Downloading files serially...
/bin/sh: aws: command not found
Command failed: mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject ; aws s3 cp s3://NDAR_Central_3/submission_27782/CHANGES /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/CHANGES --profile NDA
/bin/sh: aws: command not found
Command failed: mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject ; aws s3 cp s3://NDAR_Central_3/submission_27782/README /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/README --profile NDA
/bin/sh: aws: command not found
Command failed: mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject ; aws s3 cp s3://NDAR_Central_3/submission_27782/dataset_description.json /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/dataset_description.json --profile NDA
/bin/sh: aws: command not found
Command failed: mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline ; aws s3 cp s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/Gordon2014FreeSurferSubcortical_dparc.dlabel.nii /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/Gordon2014FreeSurferSubcortical_dparc.dlabel.nii --profile NDA
/bin/sh: aws: command not found
Command failed: mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func ; aws s3 cp s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii --profile NDA
/bin/sh: aws: command not found
Command failed: mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func ; aws s3 cp s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_desc-filtered_motion_mask.mat /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_desc-filtered_motion_mask.mat --profile NDA

Problematic commands:
s3://NDAR_Central_3/submission_27782/CHANGES
mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject ; aws s3 cp s3://NDAR_Central_3/submission_27782/CHANGES /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/CHANGES --profile NDA
s3://NDAR_Central_3/submission_27782/README
mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject ; aws s3 cp s3://NDAR_Central_3/submission_27782/README /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/README --profile NDA
s3://NDAR_Central_3/submission_27782/dataset_description.json
mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject ; aws s3 cp s3://NDAR_Central_3/submission_27782/dataset_description.json /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/dataset_description.json --profile NDA
s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/Gordon2014FreeSurferSubcortical_dparc.dlabel.nii
mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline ; aws s3 cp s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/Gordon2014FreeSurferSubcortical_dparc.dlabel.nii /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/Gordon2014FreeSurferSubcortical_dparc.dlabel.nii --profile NDA
s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii
mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func ; aws s3 cp s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_bold_atlas-Gordon2014FreeSurferSubcortical_desc-filtered_timeseries.ptseries.nii --profile NDA
s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_desc-filtered_motion_mask.mat
mkdir -p /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func ; aws s3 cp s3://NDAR_Central_3/submission_27782/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_desc-filtered_motion_mask.mat /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject/derivatives/abcd-hcp-pipeline/sub-NDARINV0FBX6KWX/ses-baselineYear1Arm1/func/sub-NDARINV0FBX6KWX_ses-baselineYear1Arm1_task-rest_desc-filtered_motion_mask.mat --profile NDA

ABCD-BIDS Downloader completed!


```

**Comment by ericearl** [comment] 2021-04-13 22:24
@kimberlylray That helps a lot, actually.  I also edited your comment to exclude subject GUIDs from the NDA site.

It looks like you have not installed the aws or awscli command and run `aws configure`.  Furthermore, it looks like you don't have permissions to write to /Volumes/psybrain/ABCD/DCanlabs-ABCD-MRIpipeline/DCAN_1subject, so check your permission there too.

**Comment by kimberlylray** [comment] 2021-04-14 16:51
@ericearl apologies, I hadn't considered the GUIDS.  I had run the requirements.txt, but you were right, I needed the AWS CLI.  
It looks to be working now.  Thanks for your help!

**Comment by ericearl** [comment] 2021-04-15 21:58
Wonderful!  You're welcome.  Closing this issue now.

**Closed by ericearl** 2021-04-15 21:58 UTC
Labels: bug, medium priority
